--- @meta

--- Authentication
--- Functions for privilege conversion, password checks, and auth-handler integration.

--- * Converts string representation of privs into table form
--- * `delim`: [Optional] String separating the privs. Defaults to `","`.
--- * Returns `{ priv1 = true, ... }`
---
--- @param str   string
--- @param delim string
--- @return table<string,boolean>
function core.string_to_privs(str, delim) end

--- * Returns the string representation of `privs`
--- * `delim`: [Optional] String to delimit privs. Defaults to `","`.
---
--- @param privs table<string,boolean>
--- @param delim string
--- @return string
function core.privs_to_string(privs, delim) end

--- Returns -> {priv1=true,...}
---
--- @param name string
--- @return table<string,boolean>
function core.get_player_privs(name) end

--- Returns `bool, missing_privs`
--- * A quickhand for checking privileges.
--- * `player_or_name`: Either a Player object or the name of a player.
--- * `...` is either a list of strings, e.g. `"priva", "privb"` or
---   a table, e.g. `{ priva = true, privb = true }`.
---
--- @param player_or_name Player|string
--- @return boolean,table
function core.check_player_privs(player_or_name, ...) end

--- * Returns true if the "password entry" for a player with name matches given
---   password, false otherwise.
--- * The "password entry" is the password representation generated by the
---   engine as returned as part of a `get_auth()` call on the auth handler.
--- * Only use this function for making it possible to log in via password from
---   external protocols such as IRC, other uses are frowned upon.
function core.check_password_entry(name, entry, password) end

--- * Convert a name-password pair to a password hash that Minetest can use.
--- * The returned value alone is not a good basis for password checks based
---   on comparing the password hash in the database with the password hash
---   from the function, with an externally provided password, as the hash
---   in the db might use the new SRP verifier format.
--- * For this purpose, use `core.check_password_entry` instead.
function core.get_password_hash(name, raw_password) end

--- Returns an IP address string for the player
---   `name`.
--- * The player needs to be online for this to be successful.
function core.get_player_ip(name) end

--- Return the currently active auth handler
--- * See the [Authentication handler definition]
--- * Use this to e.g. get the authentication data for a player:
---   `local auth_data = core.get_auth_handler().get_auth(playername)`
---
---@return AuthenticationHandlerDefinition
function core.get_auth_handler() end

--- * Must be called by the authentication handler for privilege changes.
--- * `name`: string; if omitted, all auth data should be considered modified
function core.notify_authentication_modified(name) end

--- Set password hash of
---   player `name`.
function core.set_player_password(name, password_hash) end

--- Set privileges of player
---   `name`.
---
--- @param name  string
--- @param privs table<string,boolean>  object like `{priv1=true,...}`
function core.set_player_privs(name, privs) end

--- * See `reload()` in authentication handler definition
function core.auth_reload() end
